-- =====================================================================
-- 1. DROP DATABASE NẾU CÓ
-- =====================================================================
USE tempdb;
GO
DECLARE @SQL AS NVARCHAR (1000);
IF EXISTS (SELECT 1
           FROM sys.databases
           WHERE [name] = N'FLIGHTS_Stage')
    BEGIN
        SET @SQL = N'USE [FLIGHTS_Stage];
                 ALTER DATABASE FLIGHTS_Stage SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
                 USE [tempdb];
                 DROP DATABASE FLIGHTS_Stage;';
        EXECUTE (@SQL);
    END
GO

-- =====================================================================
-- 2. CREATE DATABASE VÀ TABLES
-- =====================================================================
CREATE DATABASE FLIGHTS_Stage;
GO
USE FLIGHTS_Stage;
GO

CREATE TABLE dbo.STG_Airlines (
	IATA_CODE	CHAR(2),
	AIRLINE		NVARCHAR(100)
)

CREATE TABLE dbo.STG_Airports (
	IATA_CODE	CHAR(10),
	AIRPORT		NVARCHAR(100),
	CITY		NVARCHAR(100),
	[STATE]		CHAR(2),
	COUNTRY		NVARCHAR(50),
	LATITUDE	DECIMAL(12,9),
	LONGTITUDE	DECIMAL(12,9)
)

CREATE TABLE dbo.STG_Flights_1 (
    [DATE]					DATE,
    AIRLINE					CHAR(2),
    FLIGHT_NUMBER			INT,
    TAIL_NUMBER				VARCHAR(10),
    ORIGIN_AIRPORT			CHAR(10),
    DESTINATION_AIRPORT		CHAR(10),
    SCHEDULED_DEPARTURE		CHAR(10),
    DEPARTURE_TIME			CHAR(10),
    DEPARTURE_DELAY			FLOAT,
    TAXI_OUT				FLOAT,
    WHEELS_OFF				CHAR(10),
    SCHEDULED_TIME			FLOAT,
    ELAPSED_TIME			FLOAT,
    AIR_TIME				FLOAT,
    DISTANCE				FLOAT,
    WHEELS_ON				CHAR(10),
    TAXI_IN					FLOAT,
    SCHEDULED_ARRIVAL		CHAR(10),
    ARRIVAL_TIME			CHAR(10),
    ARRIVAL_DELAY			FLOAT,
    DIVERTED				INT,
    CANCELLED				INT,
    CANCELLATION_REASON		VARCHAR(1),
    AIR_SYSTEM_DELAY		FLOAT,
    SECURITY_DELAY			FLOAT,
    AIRLINE_DELAY			FLOAT,
    LATE_AIRCRAFT_DELAY		FLOAT,
    WEATHER_DELAY			FLOAT,
	CREATED					DATETIME2,
	MODIFIED				DATETIME2
)

CREATE TABLE dbo.STG_Flights_2 (
    [DATE]					DATE,
    AIRLINE					CHAR(2),
    FLIGHT_NUMBER			INT,
    TAIL_NUMBER				VARCHAR(10),
    ORIGIN_AIRPORT			CHAR(10),
    DESTINATION_AIRPORT		CHAR(10),
    SCHEDULED_DEPARTURE		CHAR(10),
    DEPARTURE_TIME			CHAR(10),
    DEPARTURE_DELAY			FLOAT,
    TAXI_OUT				FLOAT,
    WHEELS_OFF				CHAR(10),
    SCHEDULED_TIME			FLOAT,
    ELAPSED_TIME			FLOAT,
    AIR_TIME				FLOAT,
    DISTANCE				FLOAT,
    WHEELS_ON				CHAR(10),
    TAXI_IN					FLOAT,
    SCHEDULED_ARRIVAL		CHAR(10),
    ARRIVAL_TIME			CHAR(10),
    ARRIVAL_DELAY			FLOAT,
    DIVERTED				INT,
    CANCELLED				INT,
    CANCELLATION_REASON		VARCHAR(1),
    AIR_SYSTEM_DELAY		FLOAT,
    SECURITY_DELAY			FLOAT,
    AIRLINE_DELAY			FLOAT,
    LATE_AIRCRAFT_DELAY		FLOAT,
    WEATHER_DELAY			FLOAT,
	CREATED					DATETIME2,
	MODIFIED				DATETIME2
)

CREATE TABLE dbo.STG_Flights_3 (
    [DATE]					DATE,
    AIRLINE					CHAR(2),
    FLIGHT_NUMBER			INT,
    TAIL_NUMBER				VARCHAR(10),
    ORIGIN_AIRPORT			CHAR(10),
    DESTINATION_AIRPORT		CHAR(10),
    SCHEDULED_DEPARTURE		CHAR(10),
    DEPARTURE_TIME			CHAR(10),
    DEPARTURE_DELAY			FLOAT,
    TAXI_OUT				FLOAT,
    WHEELS_OFF				CHAR(10),
    SCHEDULED_TIME			FLOAT,
    ELAPSED_TIME			FLOAT,
    AIR_TIME				FLOAT,
    DISTANCE				FLOAT,
    WHEELS_ON				CHAR(10),
    TAXI_IN					FLOAT,
    SCHEDULED_ARRIVAL		CHAR(10),
    ARRIVAL_TIME			CHAR(10),
    ARRIVAL_DELAY			FLOAT,
    DIVERTED				INT,
    CANCELLED				INT,
    CANCELLATION_REASON		VARCHAR(1),
    AIR_SYSTEM_DELAY		FLOAT,
    SECURITY_DELAY			FLOAT,
    AIRLINE_DELAY			FLOAT,
    LATE_AIRCRAFT_DELAY		FLOAT,
    WEATHER_DELAY			FLOAT,
	CREATED					DATETIME2,
	MODIFIED				DATETIME2
)


select * from STG_Flights_3